// North Phoenix Land Leads — pulled from public GIS/Assessor records
// Regenerated by agents/phx_land_leads/find_leads.py — do not hand-edit.
window.PHX_LAND_LEADS = {
  "updated": "2026-10-01",
  "market": "North Phoenix",
  "zipCodes": [
    "85085",
    "85086",
    "85050",
    "85054",
    "85053",
    "85027",
    "85024",
    "85023",
    "85032",
    "85028",
    "85022"
  ],
  "parcelsScanned": 0,
  "newLeadsThisRun": 0,
  "leads": [],
  "history": [
    {
      "date": "2026-09-17",
      "parcelsScanned": 9707,
      "leadsFound": 600,
      "newLeads": 316
    },
    {
      "date": "2026-09-18",
      "parcelsScanned": 9707,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-19",
      "parcelsScanned": 9707,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-20",
      "parcelsScanned": 9707,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-21",
      "parcelsScanned": 9707,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-22",
      "parcelsScanned": 9707,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-23",
      "parcelsScanned": 9708,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-24",
      "parcelsScanned": 9708,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-25",
      "parcelsScanned": 9708,
      "leadsFound": 600,
      "newLeads": 300
    },
    {
      "date": "2026-09-29",
      "parcelsScanned": 9713,
      "leadsFound": 8976,
      "newLeads": 8676
    },
    {
      "date": "2026-09-30",
      "parcelsScanned": 9713,
      "leadsFound": 8976,
      "newLeads": 8676
    },
    {
      "date": "2026-10-01",
      "parcelsScanned": 0,
      "leadsFound": 0,
      "newLeads": 0
    }
  ],
  "methodologyNote": "Public-records only: Maricopa Assessor parcels (vacant land AND underused single-family-improved parcels \u2014 an existing house occupying a small share of an oversized lot, tagged TEARDOWN), Phoenix zoning + General Plan + rezoning-case layers, FEMA flood zones, plus ownership tenure/entity-type/mailing-address signals as a seller-motivation proxy. No asking price or water/sewer availability is in any public feed found \u2014 confirm those manually per lead before underwriting. Rezone targets landing on single-family zoning use a subdivision/lot-sale calculator (add a demolition cost for TEARDOWN leads); targets on multifamily/commercial zoning use a rental pro forma."
};
